app/routes.py
from flask import Blueprint, Response, current_app, render_template, render_template_string, request, redirect, url_for, session, flash
import sqlite3
import requests
import pickle
from jinja2.utils import urlize
from time import perf_counter

main = Blueprint('main', __name__)

@main.route('/')
def index():
    return render_template('login.html')

@main.route('/login', methods=['POST'])
def login():
    username = request.form['username']
    password = request.form['password']
    
    # Vulnerable SQL Query (SQL Injection)
    query = f"SELECT * FROM users WHERE username='{username}' AND password='{password}'"
    conn = sqlite3.connect('vulnerable.db')
    c = conn.cursor()
    c.execute(query)  #No parameterized query
    user = c.fetchone()
    conn.close()
    
    if user:
        session['username'] = user[1]  
        session['role'] = user[3]     
        if user[3] == 'admin':
            return redirect(url_for('main.admin_dashboard', username=username))
        else:
            return redirect(url_for('main.student_dashboard', student_id=user[0], username=username))
    else:
        return "Invalid credentials"

@main.route('/student/<student_id>')
def student_dashboard(student_id):
    conn = sqlite3.connect('vulnerable.db')
    c = conn.cursor()
    username=session['username'] 
    role= session['role'] 
    # Fetch all courses, grades, and comments for the student
    c.execute(f"SELECT course, grade, comments FROM grades WHERE student_id='{student_id}'")
    courses = c.fetchall()

    c = conn.cursor()
    c.execute('SELECT profile_photo FROM users WHERE id = ?', (student_id,))

    result = c.fetchone()
    if result:
        profile_photo = result[0]
    conn.close()
    

    return render_template('student_dashboard.html', courses=courses, username= username, role=role, student_id=student_id, profile_photo=profile_photo)

@main.route('/student/<student_id>/grades')
def grades(student_id):
    conn = sqlite3.connect('vulnerable.db')
    c = conn.cursor()
    username=session['username'] 
    role=  session['role'] 
    # Fetch all courses, grades, and comments for the student
    c.execute(f"SELECT course, grade, comments FROM grades WHERE student_id='{student_id}'")
    courses = c.fetchall()
    c = conn.cursor()
    c.execute('SELECT profile_photo FROM users WHERE id = ?', (student_id,))
    
    result = c.fetchone()
    if result:
        profile_photo = result[0]
    conn.close()

    return render_template('grades.html', courses=courses, username= username, role=role, student_id=student_id, profile_photo=profile_photo)


#Admin Dashboard
@main.route('/admin')
def admin_dashboard():
    #No role verification (causes Broken Access Control)
    conn = sqlite3.connect('vulnerable.db')
    c = conn.cursor()
    # Fetch all students, courses, grades, and comments
    c.execute('''SELECT u.username, g.course, g.grade, g.comments, g.id 
                 FROM grades g JOIN users u ON g.student_id = u.id''')
    grades = c.fetchall()
    conn.close()

    return render_template('admin_dashboard.html', grades=grades)

@main.route('/admin/edit/<grade_id>', methods=['GET', 'POST'])
def edit_grade(grade_id):
    conn = sqlite3.connect('vulnerable.db')
    c = conn.cursor()

    if request.method == 'POST':
        grade = request.form['grade']
        
        comments = request.form['comments']
        c.execute(f"UPDATE grades SET grade='{grade}', comments='{comments}' WHERE id='{grade_id}'")
        conn.commit()
        conn.close()
        return redirect(url_for('main.admin_dashboard'))
    
    c.execute(f"SELECT course, grade, comments FROM grades WHERE id='{grade_id}'")
    grade_data = c.fetchone()
    conn.close()
    return render_template('edit_grade.html', grade_data=grade_data)

@main.route('/debug')
def debug_route():
    result = 1 / 0  #Causes a ZeroDivisionError and trigger a stack trace
    return f"Result: {result}"

@main.route('/lol')
def lol_route():
   for i in range(3):
        text = "abc@" + "." * (i+1)*5000 + "!"
   lenValue = len(text)
   begin = perf_counter()
   urlize(text)
   DURATION = perf_counter() - begin
   print(f"{lenValue}: took {DURATION} seconds!")  #Causes a ZeroDivisionError and trigger a stack trace
   return f"Result: {DURATION}"

@main.route('/logout')
def logout():
    session.clear()
    return redirect("/")
    
#For Identificaiton and Authentication Failures -> users can set passw like '123'
@main.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        confirm_password = request.form['confirm_password']
        
        if password != confirm_password:
            flash("Passwords do not match", "danger")
            return render_template('register.html')
        
        try:
            with sqlite3.connect('vulnerable.db') as conn:
                c = conn.cursor()
                c.execute("INSERT INTO users (username, password, role, profile_photo) VALUES (?, ?, ?, ?)", (username, password, 'student', None))
                conn.commit()
            flash("Registration successful! You can now log in.", "success")
            return redirect(url_for('main.index'))
        except sqlite3.IntegrityError:
            flash("Username already exists. Please choose another one.", "danger")
            return render_template('register.html')
        except sqlite3.OperationalError:
            flash("Database is currently locked. Please try again later.", "danger")
            return render_template('register.html')

    return render_template('register.html')



#For SSRF -> DOS Example && Software and Data Integrity Failures -> Insecure Deserialization
@main.route('/student/<student_id>/upload_assignment/<course>', methods=['GET', 'POST'])
def upload_assignment(student_id, course):
    username = session.get('username')
    role = session.get('role')

    conn = sqlite3.connect('vulnerable.db')
    c = conn.cursor()
    c.execute('SELECT profile_photo FROM users WHERE id = ?', (student_id,))
    
    result = c.fetchone()
    if result:
        profile_photo = result[0]
  
    c = conn.cursor()

    # Check if an assignment already exists for this student and course
    c.execute("SELECT file_name, file_data FROM assignments WHERE student_id=? AND course=?", (student_id, course))
    existing_assignment = c.fetchone()

    file_name = None
    deserialized_data = None
    if existing_assignment:
        file_name = existing_assignment[0]  # Existing file name
        try:
            # Insecure Deserialization
            deserialized_data = pickle.loads(existing_assignment[1])
        except Exception as e:
            deserialized_data = f"Error deserializing data: {str(e)}"

    if request.method == 'POST':
        uploaded_file = request.files.get('file')

        # Vulnerable: No size or type validation (SSRF)
        if uploaded_file:
            # Serialize file data and store it in the database (Insecure Serialization)
            serialized_data = pickle.dumps(uploaded_file.read())
            file_name = uploaded_file.filename
            if existing_assignment:
                # Update existing assignment
                c.execute("UPDATE assignments SET file_data=?, file_name=? WHERE student_id=? AND course=?", 
                          (serialized_data, file_name, student_id, course))
            else:
                # New assignment
                c.execute("INSERT INTO assignments (student_id, course, file_data, file_name) VALUES (?, ?, ?, ?)", 
                          (student_id, course, serialized_data, file_name))
            conn.commit()
            conn.close()
            return render_template('successfully_upload.html', 
                                   course=course, 
                                   student_id=student_id, 
                                   username=username, 
                                   role=role, profile_photo=profile_photo)

        return "No file uploaded!", 400

    conn.close()
    return render_template('upload_assignment.html', 
                           course=course, 
                           student_id=student_id, 
                           username=username, 
                           role=role, 
                           file_name=file_name, 
                           deserialized_data=deserialized_data, profile_photo=profile_photo)

@main.route('/upload_photo/<student_id>', methods=['GET', 'POST'])
def upload_photo(student_id):
    username = session.get('username')
    role = session.get('role')
    profile_photo = None

    conn = sqlite3.connect('vulnerable.db')
    c = conn.cursor()

    # Fetch the current profile photo
    c.execute('SELECT profile_photo FROM users WHERE id = ?', (student_id,))
    result = c.fetchone()
    if result:
        profile_photo = result[0]
    conn.close()

    if request.method == 'POST':
        photo_url = request.form.get('photo_url')
        print(photo_url)
        
        if photo_url:
            try:
                # Fetch the image data from the provided URL
                response = requests.get(photo_url)
                response.raise_for_status()  # Raise an HTTPError for bad responses
                file_data = response.content  # Binary content of the image

                # Store the image in the database
                conn = sqlite3.connect('vulnerable.db')
                c = conn.cursor()
                c.execute('UPDATE users SET profile_photo = ? WHERE id = ?', (file_data, student_id))
                conn.commit()
                conn.close()

                flash('Profile photo uploaded successfully!')
                return redirect(url_for('main.upload_photo', student_id=student_id))

            except requests.exceptions.RequestException as e:
                flash(f'Failed to fetch the photo from the URL: {str(e)}')

app/templates/admin_dashboard.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BUCourse</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background: #eeeef0;
        }

        .navbar {
            display: flexbox;
            justify-content: space-between;
            align-items: center;
            padding: 15px 20px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.2);
            background-image: url("{{ url_for('static', filename='navbar.png') }}");
        }

        .navbar img {
            height: 90px;
            /* Adjust logo size */
            padding: 0.1rem;
        }

        .navbar .right-links {
            display: flex;
            align-items: center;
        }

        .navbar a {
            color: white;

            margin-left: 20px;
            font-size: 14px;
            padding: 8px 10px;
            background-color: #0073C1;
            /* Blue for the button */
            border-radius: 0px;
            transition: background-color 0.3s ease;
        }

        .navbar a:hover {
            background-color: #005A9E;
        }

        /* Middle dark bar styling */
        .middle-bar {
            background-color: #3E4C56;
            /* Slightly lighter dark bar */
            height: 3rem;
            display: flex;
            align-items: center;

        }

        .content {
            padding: 2em;
            text-align: center;
        }

        table {
            margin: 0 auto;
            width: 50%;
            border-collapse: collapse;
        }

        table,
        th,
        td {
            border: 1px solid #ddd;
        }

        th,
        td {
            padding: 1em;
            text-align: center;
        }

        th {
            background-color: #f4f4f4;
        }

        .initialBox {
            margin-top: 1.5rem;
            margin-left: 4rem;
            margin-right: 4rem;
            background-color: white;
            padding-bottom: 5rem;

        }

        .loginText {
            color: #3E4C56;
            font-weight: 900;
            padding-bottom: 1rem;

        }

        .cardBg {
            background-color: #eeeef0;
            border: none;
            border-radius: 0rem;
        }

        .formInp {
            padding-bottom: 2.5rem;
        }

        .inputPd {
            padding-bottom: 1rem;
        }

        .inputStyl {
            border: none;
            border-radius: 0rem;
            height: 2.6rem;
        }

        .lostPssw {
            font-size: 14px;
        }



        .dropdown-menu {
            position: absolute;
            top: 60px;
            background-color: white;
            border: 1px solid #ccc;
            border-radius: 5px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.2);
            display: none;
            z-index: 1000;
            width: 150px;
        }

        .dropdown-menu a {
            display: block;
            padding: 10px 15px;
            color: #333;
            text-decoration: none;
            background-color: white;
        }

        .dropdown-menu a:hover {
            background-color: #f4f4f4;
        }

        .dropdown-menu hr {
            margin: 0;
            border: none;
            border-top: 1px solid #ddd;
        }

        .user-profile {
            position: relative;
            display: flex;
            align-items: center;
            gap: 10px;
            cursor: pointer;
        }

        /* Notification Badge */
        .notification {
            position: relative;
        }

        .notification-badge {
            position: absolute;
            top: -8px;
            left: 8px;
            background-color: red;
            color: white;
            font-size: 8px;
            font-weight: bold;
            border-radius: 50%;
            padding: 3px 6px;
        }

        /* User Name Styling */
        .user-name {
            font-size: 16px;
            color: #2c577b;
            font-weight: bold;
        }


        .icn {
            color: #758e9f;
        }

        .header {
            color: #6e6f6f;
            padding-bottom: 1rem;
            font-size: 28px;
            font-weight: 600;
        }

        .wrapper {
            display: flex;
            flex-direction: column;
            padding: 2rem;
        }
        .profPic {
            height: 100px;
            width: 70px;
            border-radius: 50%;
            /* Makes the image circular */
            border: 2px solid #afbaf0;
            margin-right: 1rem;
            margin-left: 1rem;

        }

        table {
            margin-left: 0;
            /* Align the table to the left */
            width: 50%;
            /* Optional: Adjust as needed */
            border-collapse: collapse;
            padding: 2rem;
        }
    </style>
</head>

<body>
    <div class="initialBox">
        <div class="navbar">

            <div>
                <img src="{{ url_for('static', filename='logo.png') }}" alt="Logo">
            </div>

            <div class="user-profile">

                <div class="notification">
                    <i class="fas fa-bell icn"></i>
                    <span class="notification-badge">12</span>
                </div>
                <div>
                    <i class="fas fa-comment icn"></i>
                </div>
                <div class="user-profile" onclick="toggleDropdown()">
                    <span class="user-name">Admin</span>
                    {% if profile_photo %}
                    <img src="{{ url_for('main.get_profile_photo', student_id=student_id) }}" alt="Profile"
                        class="profPic">
                    {% else %}
                    <img src="{{ url_for('static', filename='user.png') }}" alt="Profile" class="profPic">
                    {% endif %}
                    <div class="dropdown-menu" id="dropdownMenu">
                        <a href="#">Profile</a>
                        <a href="{{ url_for('main.grades', student_id=student_id) }}">Grades</a>
                        <a href="#">Calendar</a>
                        <a href="#">Private files</a>
                        <a href="#">Preferences</a>
                        <hr>
                        <a href="/logout"><i class="fas fa-sign-out-alt"></i> Log out</a>
                    </div>
                </div>
            </div>
        </div>

        <div class="middle-bar">

        </div>
        <div class="wrapper">
            <div class="header"> All Students' Grades</div>

            <table>
                <tr>
                    <th>Student</th>
                    <th>Course</th>
                    <th>Grade</th>
                    <th>Comments</th>
                    <th>Actions</th>
                </tr>
                {% for username, course, grade, comments, grade_id in grades %}
                <tr>
                    <td>{{ username }}</td>
                    <td>{{ course }}</td>
                    <td>{{ grade }}</td>
                    <td>{{ comments }}</td>
                    <td>
                        <a href="{{ url_for('main.edit_grade', grade_id=grade_id) }}">Edit</a>
                    </td>
                </tr>
                {% endfor %}
            </table>
        </div>
        <!-- JavaScript to Toggle the Dropdown -->
        <script>
            function toggleDropdown() {
                const dropdownMenu = document.getElementById('dropdownMenu');
                dropdownMenu.style.display = (dropdownMenu.style.display === 'block') ? 'none' : 'block';
            }

            // Close the dropdown if clicked outside
            window.onclick = function (event) {
                const dropdownMenu = document.getElementById('dropdownMenu');
                const userProfile = document.querySelector('.user-profile');
                if (!userProfile.contains(event.target)) {
                    dropdownMenu.style.display = 'none';
                }
            }
        </script>
</body>

</html>

app/templates/edit_grade.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BUCourse</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background: #eeeef0;
        }
        .navbar {
            display: flexbox;
            justify-content: space-between;
            align-items: center;
            padding: 15px 20px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.2);
            background-image: url("{{ url_for('static', filename='navbar.png') }}");
        }

        .navbar img {
            height: 90px; /* Adjust logo size */
            padding: 0.1rem;
        }

        .navbar .right-links {
            display: flex;
            align-items: center;
        }

        .navbar a {
            color: white;
           
            margin-left: 20px;
            font-size: 14px;
            padding: 8px 10px;
            background-color: #0073C1; /* Blue for the button */
            border-radius: 0px;
            transition: background-color 0.3s ease;
        }

        .navbar a:hover {
            background-color: #005A9E; 
        }

        /* Middle dark bar styling */
        .middle-bar {
            background-color: #3E4C56; /* Slightly lighter dark bar */
            height: 3rem;
            display: flex;
            align-items: center;
           
        }           
        .content {
            padding: 2em;
            text-align: center;
        }
        table {
            margin: 0 auto;
            width: 50%;
            border-collapse: collapse;
        }
        table, th, td {
            border: 1px solid #ddd;
        }
        th, td {
            padding: 1em;
            text-align: center;
        }
        th {
            background-color: #f4f4f4;
        }
        .initialBox{
            margin-top: 1.5rem;
            margin-left: 4rem;
            margin-right: 4rem;
            background-color: white;
            padding-bottom: 5rem;
            
        }
        .loginText{
            color:#3E4C56;
            font-weight:900;
            padding-bottom: 1rem;

        }
        .cardBg{
            background-color: #eeeef0;
            border: none;
            border-radius: 0rem;
        }
        .formInp{
            padding-bottom: 2.5rem;
        }
        .inputPd{
            padding-bottom: 1rem;
        }
        .inputStyl{
            border: none;
            border-radius: 0rem;
            height: 2.6rem;
        }
        .lostPssw{
            font-size: 14px;
        }
  


        .dropdown-menu {
            position: absolute;
            top: 60px; 
            background-color: white;
            border: 1px solid #ccc;
            border-radius: 5px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.2);
            display: none; 
            z-index: 1000;
            width: 150px;
        }

        .dropdown-menu a {
            display: block;
            padding: 10px 15px;
            color: #333;
            text-decoration: none;
            background-color: white;
        }

        .dropdown-menu a:hover {
            background-color: #f4f4f4;
        }

        .dropdown-menu hr {
            margin: 0;
            border: none;
            border-top: 1px solid #ddd;
        }
        .user-profile {
            position: relative;
            display: flex;
            align-items: center;
            gap: 10px;
            cursor: pointer;
        }
    /* Notification Badge */
    .notification {
        position: relative;
    }

    .notification-badge {
        position: absolute;
        top: -8px;
        left: 8px;
        background-color: red;
        color: white;
        font-size: 8px;
        font-weight: bold;
        border-radius: 50%;
        padding: 3px 6px;
    }

    /* User Name Styling */
    .user-name {
        font-size: 16px;
        color: #2c577b;
        font-weight: bold;
    }

    
    .icn{
        color: #758e9f;
    }
    .header{
        color:#6e6f6f;
        padding-bottom: 1rem;
        font-size: 28px;
        font-weight: 600;
    }
    .wrapper{
        display: flex;
        flex-direction: column;
        padding: 2rem;
    }
    table {
    margin-left: 0; /* Align the table to the left */
    width: 50%; /* Optional: Adjust as needed */
    border-collapse: collapse;
    padding: 2rem;
    }
    form {
            background-color: #d2d6d6;
            margin: 30px 20px;
            padding: 20px;
            width: 90%;
            max-width: 400px;
            border-radius: 8px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            text-align: left;
        }

        label {
            font-weight: bold;
            color: #4a4a4a;
            display: block;
            margin-bottom: 5px;
        }

        input[type="text"],
        textarea {
            width: 100%;
            padding: 10px;
            margin-bottom: 15px;
            border: 1px solid #ccc;
            border-radius: 5px;
            font-size: 14px;
        }

        textarea {
            resize: vertical;
            height: 100px;
        }

        button {
            background-color: #2b5069;
            color: white;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            font-size: 14px;
            cursor: pointer;
            transition: background-color 0.3s ease;
            margin: 0 auto;
        }

        button:hover {
            background-color: #005a9e;
        }

        button:active {
            background-color: #004a80;
        }

        @media (max-width: 600px) {
            form {
                width: 90%;
            }

            button {
                width: 100%;
            }
        }
    </style>
</head>
<body>
    <div class="initialBox">
        <div class="navbar">

            <div>
                <img src="{{ url_for('static', filename='logo.png') }}" alt="Logo">
            </div>
        
            <div class="user-profile">
                
                <div class="notification">
                    <i class="fas fa-bell icn"></i>
                    <span class="notification-badge">12</span>
                </div>
                <div >
                    <i class="fas fa-comment icn"></i> 
                </div>
                <div class="user-profile" onclick="toggleDropdown()">
                <span class="user-name">Admin</span>
                {% if profile_photo %}
                <img src="{{ url_for('main.get_profile_photo', student_id=student_id) }}" alt="Profile" class="profPic">
                {% else %}
                <img src="{{ url_for('static', filename='user.png') }}" alt="Profile" class="profPic">
                {% endif %}
                <div class="dropdown-menu" id="dropdownMenu">
                    <a href="#">Profile</a>
                    <a href="{{ url_for('main.grades', student_id=student_id) }}">Grades</a>
                    <a href="#">Calendar</a>
                    <a href="#">Private files</a>
                    <a href="{{ url_for('main.upload_photo', student_id=student_id) }}">Update Profile Photo</a>
                    <hr>
                    <a href="/logout"><i class="fas fa-sign-out-alt"></i> Log out</a>
                </div>
                </div>
            </div>
        </div>
        
        <div class="middle-bar">
        
        </div>
     <div class="wrapper">
            <div class="header">Edit Grade for {{ grade_data[0] }}</div>
            <form method="POST">
                <label for="grade">Grade:</label><br>
                <input type="text" id="grade" name="grade" value="{{ grade_data[1] }}" required><br><br>
                
                <label for="comments">Comments:</label><br>
                <textarea id="comments" name="comments" required>{{ grade_data[2] }}</textarea><br><br>
                
                <button type="submit">Save Changes</button>
            </form>
        </div>
    <!-- JavaScript to Toggle the Dropdown -->
    <script>
        function toggleDropdown() {
            const dropdownMenu = document.getElementById('dropdownMenu');
            dropdownMenu.style.display = (dropdownMenu.style.display === 'block') ? 'none' : 'block';
        }

        // Close the dropdown if clicked outside
        window.onclick = function(event) {
            const dropdownMenu = document.getElementById('dropdownMenu');
            const userProfile = document.querySelector('.user-profile');
            if (!userProfile.contains(event.target)) {
                dropdownMenu.style.display = 'none';
            }
        }
    </script>
</body>


</html>